version: '3'
services:
  api:
    image: leetun2k2/api-dashboard:api
    ports:
      - "5000:5000"

  client:
    image: leetun2k2/api-dashboard:client
    ports:
      - "80:3000"
    depends_on:
      - api
