FROM python:3.10

WORKDIR /app

RUN python -m venv venv

ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY app.py .flaskenv ./

COPY database ./database

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]