version: '3'
services:
  dashboard:
    image: leetun2k2/dashboard
    ports:
      - 3000:3000

  nginx:
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - dashboard
