# This Dockerfile builds the API only.
FROM python:3.10

WORKDIR /app

COPY requirements.txt app.py ./
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY database ./database

EXPOSE 5000

CMD ["python", "app.py"]