name: Add NPM User

on: [push]

jobs:
  add-npm-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to NPM
        run: |
          cd api-dashboard
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"
          npm whoami
